name: Unit Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: [self-hosted, aur0]
    strategy:
      matrix:
        deno-version: [v2.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Run all tests
        run: deno task test
